version: "3.1"

services:
  db_postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  adminer:
    container_name: barber_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
